{{- if and (not .Values.ssh.existingHostKeySecret) .Values.ssh.hostKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.sshHostKeySecretName" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  # SSH host key (base64 encoded)
  {{ .Values.ssh.hostKeySecretKey }}: {{ .Values.ssh.hostKey }}
{{- end }}
