apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- if .Values.service.grpc.enabled }}
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.gateway.grpcPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.gnmi.enabled }}
    - name: gnmi
      port: {{ .Values.service.gnmi.port }}
      targetPort: {{ .Values.gateway.gnmiPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.ssh.enabled }}
    - name: ssh
      port: {{ .Values.service.ssh.port }}
      targetPort: {{ .Values.gateway.sshPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.netconf.enabled }}
    - name: netconf
      port: {{ .Values.service.netconf.port }}
      targetPort: {{ .Values.gateway.netconfPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
